### ISSUE TITLE
how make login ?

### ISSUE THREAD

**Issue by abdoojaber** [erfanshekari/woocommerce_client#2]

**Comment by erfanshekari** [comment]
You can use API Key of WooCommerce Rest API
`final api = Woocommerce(
    baseURL: 'http://woocommerce.ir',
    consumerKey: 'consumer_key',
    consumerSecret: 'consumer_secret',
  );`

**Comment by abdoojaber** [comment]
plz complete code for login i dont know how make this

**Comment by ropiudindev** [comment]
seems like not provided by this library
